name: aitelier
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  crypto: ^3.0.7
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^10.0.0
  git: ^2.3.2
  http: ^1.6.0
  logger: ^2.6.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.41
  ulid: ^2.0.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.30.0
  build_runner: ^2.10.4

flutter:

  assets:
    - assets/purposes/
  uses-material-design: true
